spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    application:
      name: web-crawler

server:
  port: 8081
  servlet:
    contextPath: /web-crawler

website:
  url: https://www.baeldung.com/